config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  get "homepage", to: "homepage#show", as: "homepage"

  devise_for :users
  get "users/:id", to: "users#show", as: "user_profile"

  resources :events do
    member do
      post "join"
      delete "leave"
    end

    collection do
      get :past
      get :ongoing
      get :upcoming
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events, dependent: :destroy

  has_many :user_events_attendees, -> { attendees }, class_name: "UserEvent"
  has_many :attendees, through: :user_events_attendees, source: :user

  has_many :user_events_organizers, -> { organizers }, class_name: "UserEvent"
  has_many :organizers, through: :user_events_organizers, source: :user

  validates :title, presence: true
  validates :date, presence: true
  validates :ending_date, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :location_name, presence: true
  validates :visibility, presence: true

  enum :visibility, { public_event: 0, private_event: 1 }, default: :public_event

  scope :past, -> { where("ending_date < ?", Time.current) }
  scope :ongoing, -> { where("date <= ? AND ending_date >= ?", Time.current, Time.current) }
  scope :upcoming, -> { where("date > ?", Time.current) }

  def past?
    ending_date < Time.current
  end

  def ongoing?
    date <= Time.current && ending_date >= Time.current
  end

  def upcoming?
    date > Time.current
  end

  def formatted_date
    date.strftime("%b %d, %Y at %H:%M")
  end

  def formatted_ending_date
    ending_date.strftime("%b %d, %Y at %H:%M")
  end

  def duration
    time_diff = ending_date - date
    formatted_duration(time_diff)
  end

  def starting_for
    return "Ongoing" if ongoing?
    return "Event has ended" if past?

    time_diff = date - Time.current
    formatted_duration(time_diff)
  end

  private

  def formatted_duration(time_diff)
    time_diff_parts = ActiveSupport::Duration.build(time_diff.to_i).parts.except(:seconds)
    time_diff_parts.map { |key, value| "#{value} #{key.to_s.pluralize(value)}" }.join(" ")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_events, dependent: :destroy

  has_many :user_events_attendee, -> { where(role: :attendee) }, class_name: "UserEvent"
  has_many :attended_events, through: :user_events_attendee, source: :event

  has_many :user_events_organizer, -> { where(role: :organizer) }, class_name: "UserEvent"
  has_many :organized_events, through: :user_events_organizer, source: :event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :role, presence: true

  enum :role, { organizer: 0, attendee: 1 }

  scope :organizers, -> { where(role: :organizer) }
  scope :attendees, -> { where(role: :attendee) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy join leave ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :authorize_event_creator, only: %i[ edit destroy ]

  def index
    if user_signed_in?
      # @events = Event.all
      redirect_to upcoming_events_path, status: :see_other
    else
      redirect_to homepage_path, status: :see_other
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.organizers << current_user

    if @event.save
      redirect_to @event, notice: "Event was successfully created."
    else
      flash.now[:error] = "Something went wrong."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated.", status: :see_other
    else
      flash.now[:error] = "Something went wrong."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy!

    redirect_to events_path, notice: "Event was successfully destroyed.", status: :see_other
  end

  def join
    unless helpers.joined_event?(@event)
      @event.attendees << current_user
      flash[:success] = "You have successfully joined the event."
    else
      flash[:notice] = "You have already joined the event."
    end

    redirect_to request.referrer
  end

  def leave
    if helpers.joined_event?(@event)
      @event.attendees.destroy(current_user)
      flash[:success] = "You have successfully left the event."
    else
      flash[:notice] = "You have already left the event."
    end

    redirect_to request.referrer
  end

  def past
    @events = Event.past
  end

  def ongoing
    @events = Event.ongoing
  end

  def upcoming
    @events = Event.upcoming
  end

  private

  def set_event
    @event = Event.find(params.expect(:id))
  end

  def event_params
    params.expect(event: %i[ title description date ending_date latitude longitude location_name ])
  end

  def authorize_event_creator
    unless @event.organizers.include?(current_user)
      flash[:error] = "Something went wrong"
      redirect_to events_path
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type.to_sym
    when :success then "bg-green-700"
    when :notice then "bg-blue-700"
    when :alert  then "bg-red-700"
    when :error then "bg-red-700"
    end
  end

  def flash_icon(type)
    case type.to_sym
    when :success then '<i class="fa-solid fa-circle-check"></i>'.html_safe
    when :notice then '<i class="fa-solid fa-circle-info"></i>'.html_safe
    when :alert then '<i class="fa-solid fa-circle-xmark"></i>'.html_safe
    when :error then '<i class="fa-solid fa-circle-xmark"></i>'.html_safe
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def joined_event?(event)
    event.attendees.include?(current_user)
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_card.html.erb
<div class="flex flex-col gap-4 shadow-black/50 shadow-lg p-4 border rounded-md">
  <header class="flex justify-between gap-4">
    <div>
      <strong class="block mb-1 text-lg"><%= event.title %></strong>
      <p class="block mb-1 text-[0.925rem]"><i class="fa-solid fa-calendar"></i> <%= event.date.to_s[0..-8] %></p>
      <p class="">
        <%= event.description %>
      </p>
    </div>

    <div class="flex flex-col space-y-1 w-20 sm:w-auto">
      <%= link_to "Show", event, class: "inline-block bg-gray-100 hover:bg-gray-50 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-center" %>

      <% if event.organizers.include?(current_user) %>
        <%= link_to "Edit", edit_event_path(event), class: "inline-block bg-blue-600 hover:bg-blue-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-white text-center" %>
      <% end %>
    </div>
  </header>

  <div class="max-h-60">
    <%= 
      render partial: "shared/map_location", 
      locals: {
        map_id: "map-#{event.id}", 
        latitude: event.latitude, 
        longitude: event.longitude,
        location_name: event.location_name,
        has_location_errors: false,
        has_location_name_errors: false,
        editable: false
      }
    %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "contents") do |form| %>
  <div class="flex flex-wrap lg:flex-nowrap gap-4 w-full">
    <div class="grow basis-1/2">
      <div class="my-2 mt-5">
        <%= form.label :title, class: "font-bold" %>
        <%= form.text_field :title, class: "block shadow-sm mt-1 px-3 py-2 border rounded-md w-full #{event.errors[:title].any? ? "border-red-700 border-2" : "border-gray-400 focus:outline-blue-600"}" %>

        <ul class="text-red-600">
          <% event.errors.full_messages_for(:title).each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

      <div class="flex sm:flex-row flex-col gap-x-4">
        <div class="flex-grow my-2 sm:w-56">
          <%= form.label :date, class: "font-bold" %>
          <%= form.datetime_field :date, class: "block shadow-sm mt-1 px-3 py-2 border rounded-md w-full #{event.errors[:date].any? ? "border-red-700 border-2" : "border-gray-400 focus:outline-blue-600"}" %>

          <ul class="text-red-600">
            <% event.errors.full_messages_for(:date).each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>

        <div class="flex-grow my-2 sm:w-56">
          <%= form.label :ending_date, class: "font-bold" %>
          <%= form.datetime_field :ending_date, class: "block shadow-sm mt-1 px-3 py-2 border rounded-md w-full #{event.errors[:ending_date].any? ? "border-red-700 border-2" : "border-gray-400 focus:outline-blue-600"}" %>

          <ul class="text-red-600">
            <% event.errors.full_messages_for(:ending_date).each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="mt-5">
        <%= form.label :description, class: "font-bold" %>
        <%= form.textarea :description, rows: 5, class: "block shadow-sm mt-1 px-3 py-2 border rounded-md w-full h-60 #{event.errors[:description].any? ? "border-red-700 border-2" : "border-gray-400 focus:outline-blue-600"}" %>
      </div>
    </div>

    <div class="flex flex-col grow basis-1/2">
      <label class="mt-5 mb-1 font-bold">Location</label>
      <%= 
        render partial: "shared/map_location", 
        locals: {
          map_id: "map-#{@event.id}", 
          latitude: @event.latitude, 
          longitude: @event.longitude,
          location_name: @event.location_name,
          has_location_errors: event.errors[:latitude].any? || event.errors[:longitude].any?,
          has_location_name_errors: event.errors[:location_name].any?,
          editable: true
        }
      %>

      <ul class="text-red-600">
        <% event.errors.full_messages_for(:location).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="inline-block mt-5">
    <%= form.submit class: "inline-block bg-blue-600 hover:bg-blue-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-white cursor-pointer" %>
  </div>
<% end %>

app/views/events/_group_links.html.erb
<div class="flex bg-gray-50 my-3 border border-gray-400 rounded-md overflow-hidden">
  <%= link_to "Upcoming Events", upcoming_events_path, class: "block px-4 py-2 text-center grow base-1/3 w-1/3 #{"bg-slate-600 text-white font-bold" if current_page?(upcoming_events_path)}" %>
  <%= link_to "Ongoing Events", ongoing_events_path, class: "block px-4 py-2 border-gray-400 border-x text-center grow base-1/3 w-1/3 #{"bg-slate-600 text-white font-bold" if current_page?(ongoing_events_path)}" %>
  <%= link_to "Past Events", past_events_path, class: "block px-4 py-2 text-center grow base-1/3 w-1/3 #{"bg-slate-600 text-white font-bold" if current_page?(past_events_path)}" %>
</div>

app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <h1 class="font-bold text-4xl">Editing event</h1>

  <%= render "form", event: @event %>

  <div class="inline-flex gap-2 ml-1">
    <%= link_to "Show this event", @event, class: "inline-block bg-gray-100 hover:bg-gray-50 mt-2 sm:mt-0 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-center" %>
    <%= link_to "Back to events", events_path, class: "inline-block bg-gray-100 hover:bg-gray-50 mt-2 sm:mt-0 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-center" %>
    <%= button_to "Destroy", @event, method: :delete, class: "bg-red-600 hover:bg-red-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-white cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/events/index.html.erb
<% content_for :title, "Events" %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Events</h1>
    <%= link_to "New event", new_event_path, class: "block bg-green-600 hover:bg-green-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md font-medium text-white" %>
  </div>

  <div class="flex bg-gray-50 my-3 border border-gray-400 rounded-md overflow-hidden">
    <%= link_to "Upcoming Events", upcoming_events_path, class: "block px-4 py-2 text-center grow base-1/3 w-1/3 #{"bg-slate-600 text-white font-bold" if current_page?(upcoming_events_path)}" %>
    <%= link_to "Past Events", past_events_path, class: "block px-4 py-2 border-gray-400 border-x text-center grow base-1/3 w-1/3 #{"bg-slate-600 text-white font-bold" if current_page?(past_events_path)}" %>
    <%= link_to "Ongoing Events", ongoing_events_path, class: "block px-4 py-2 text-center grow base-1/3 w-1/3 #{"bg-slate-600 text-white font-bold" if current_page?(ongoing_events_path)}" %>
  </div>

  <div id="events" class="gap-8 sm:gap-4 lg:gap-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mt-4 min-w-full">
    <% if @events.any? %>
      <% @events.each do |event| %>
        <%= render "event_card", event: event %>
      <% end %>
    <% else %>
      <p class="my-10 text-center">No events found.</p>
    <% end %>
  </div>
<% end %>

app/views/events/new.html.erb
<% content_for :title, "New event" %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <h1 class="font-bold text-4xl">New event</h1>

  <%= render "form", event: @event %>

  <%= link_to "Back to events", events_path, class: "inline-block bg-gray-100 hover:bg-gray-50 mt-2 sm:mt-0 sm:ml-2 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto font-medium text-center" %>
<% end %>

app/views/events/ongoing.html.erb
<% content_for :title, "Events" %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Events</h1>
    <%= link_to "New event", new_event_path, class: "block bg-green-600 hover:bg-green-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md font-medium text-white" %>
  </div>

  <%= render "events/group_links" %>

  <div id="events" class="gap-8 sm:gap-4 lg:gap-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mt-4 min-w-full">
    <% if @events.any? %>
      <% @events.onging.each do |event| %>
        <%= render "event_card", event: event %>
      <% end %>
    <% else %>
      <p class="my-10 text-center">No events found.</p>
    <% end %>
  </div>
<% end %>

app/views/events/past.html.erb
<% content_for :title, "Events" %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Events</h1>
    <%= link_to "New event", new_event_path, class: "block bg-green-600 hover:bg-green-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md font-medium text-white" %>
  </div>

  <%= render "events/group_links" %>

  <div id="events" class="gap-8 sm:gap-4 lg:gap-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mt-4 min-w-full">
    <% if @events.any? %>
      <% @events.past.each do |event| %>
        <%= render "event_card", event: event %>
      <% end %>
    <% else %>
      <p class="my-10 text-center">No events found.</p>
    <% end %>
  </div>
<% end %>

app/views/events/show.html.erb
<% content_for :title, @event.title %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <h1 class="font-bold text-4xl"><%= @event.title %></h1>

  <div id="<%= dom_id @event %>" class="my-5 w-full sm:w-auto">
    <div class="flex flex-wrap md:flex-nowrap gap-4 w-full">
      <div class="space-y-5 grow basis-1/2">
        <div class="flex gap-2">
          <div class="font-bold"><i class="fa-solid fa-user-tie"></i> Organized by:</div>
          <div class=""><%= @event.organizers.map { |organizer| organizer.username }.join(", ") %></div>
        </div>

        <div class="flex lg:sm:flex-row flex-col md:flex-col gap-2 -mt-4 w-full">
          <div class="bg-gray-50 p-2 py-1.5 border border-gray-300 rounded-md grow basis-1/2">
            <strong class="block mb-1"><i class="fa-regular fa-calendar"></i> Date:</strong>
            <%= @event.formatted_date %>
          </div>

          <div class="bg-gray-50 p-2 py-1.5 border border-gray-300 rounded-md grow basis-1/2">
            <strong class="block mb-1"><i class="fa-regular fa-calendar"></i> Ending date:</strong>
            <%= @event.formatted_ending_date %>
          </div>
        </div>

        <div class="flex lg:sm:flex-row flex-col md:flex-col gap-2 -mt-3 w-full">
          <div class="bg-gray-50 p-2 py-1.5 border border-gray-300 rounded-md grow basis-1/2">
            <strong class="block mb-1"><i class="fa-regular fa-hourglass-half"></i> Starts for:</strong>
            <%= @event.starting_for %>
          </div>

          <div class="bg-gray-50 p-2 py-1.5 border border-gray-300 rounded-md grow basis-1/2">
            <strong class="block mb-1"><i class="fa-regular fa-clock"></i> Duration:</strong>
            <%= @event.duration %>
          </div>
        </div>

        <div>
          <strong class="block mb-1">Description:</strong>
          <div class="bg-gray-50 p-4 py-3 border border-gray-300 rounded-md min-h-64 overflow-auto resize-y">
            <% if @event.description.present? %>
              <%= @event.description %>
            <% else %>
              <em>No description</em>
            <% end %>
          </div>
        </div>

        <div class="flex gap-2 -mt-3">
          <strong class="block"><i class="mr-1 fa-solid fa-users"></i> Attendees:</strong>
          <div class="">
            <%= @event.attendees.count %>
            <% if @event.attendees.include?(current_user) %>
              (including you)
            <% end %>
          </div>
        </div>
      </div>

      <div class="flex flex-col grow basis-1/2">
        <strong class="block mb-1">Location:</strong>
        <%= 
        render partial: "shared/map_location", 
        locals: {
          map_id: "map-#{@event.id}", 
          latitude: @event.latitude, 
          longitude: @event.longitude,
          location_name: @event.location_name,
          has_location_errors: false,
          has_location_name_errors: false,
          editable: false
        }
      %>
      </div>
    </div>
  </div>

  <% if joined_event?(@event) %>
    <%= link_to "Leave event", leave_event_path, data: { turbo_method: :delete }, class: "inline-block bg-red-600 hover:bg-red-500 mt-2 sm:mt-0 mr-1 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto text-white text-center" %>
  <% else %>
    <%= link_to "Join event", join_event_path, data: { turbo_method: :post}, class: "inline-block bg-green-600 hover:bg-green-500 mt-2 sm:mt-0 mr-1 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto text-white text-center" %>
  <% end %>

  <%= link_to "Back to events", events_path, class: "inline-block bg-gray-100 hover:bg-gray-50 mt-2 sm:mt-0 mr-1 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto text-center" %>

  <% if @event.organizers.include?(current_user) %>
    <%= link_to "Edit this event", edit_event_path(@event), class: "inline-block bg-blue-600 hover:bg-blue-500 mt-2 sm:mt-0 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full sm:w-auto text-white text-center" %>
    <%= button_to "Destroy this event", @event, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-1", class: "bg-red-600 hover:bg-red-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md w-full text-white cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  <% end %>
<% end %>

app/views/events/upcoming.html.erb
<% content_for :title, "Events" %>

<%= render layout: "shared/centered_container_wrapper" do %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Events</h1>
    <%= link_to "New event", new_event_path, class: "block bg-green-600 hover:bg-green-500 px-4 py-2 border-[0.5px] border-neutral-500 rounded-md font-medium text-white" %>
  </div>

  <%= render "events/group_links" %>

  <div id="events" class="gap-8 sm:gap-4 lg:gap-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mt-4 min-w-full">
    <% if @events.any? %>
      <% @events.upcoming.each do |event| %>
        <%= render "event_card", event: event %>
      <% end %>
    <% else %>
      <p class="my-10 text-center">No events found.</p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="bg-slate-800 p-4 h-16 text-gray-50">
  <div class="flex justify-between items-center gap-8 mx-auto h-full container">
    <div class="font-bold text-2xl">
      <%= link_to "EventoMundo", root_path %>
    </div>

    <% if user_signed_in? %>
      <div data-controller="user-menu" data-action="click->user-menu#showMenu" class="relative h-full">
        <div class="flex justify-center items-center gap-2 h-full cursor-pointer">
          <i class="h-5.5 text-2xl fa-solid fa-circle-user"></i>
          <%= current_user.username %>
          <i data-user-menu-target="caret" class="text-sm fa-caret-down fa-solid"></i>
        </div>

        <ul data-user-menu-target="menu" style="display: none" class="top-full right-0 absolute bg-neutral-50 mt-2 border rounded-sm w-40 overflow-hidden text-black">
          <li class="hover:bg-neutral-300">
            <%= button_to user_profile_path(current_user.id), method: :get, class: "px-3 py-2 w-full h-full text-left cursor-pointer" do %>
              <i class="fa-solid fa-user"></i> Profile
            <% end %>
          </li>
          <li class="hover:bg-neutral-300">
            <%= button_to destroy_user_session_path, method: :get, class: "px-3 py-2 w-full h-full text-left cursor-pointer" do %>
              <i class="fa-right-from-bracket fa-solid"></i> Log Out
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>
</header>

app/views/layouts/_notifications.html.erb
<div class="right-0 bottom-0 z-50 fixed flex flex-col-reverse p-4 w-[360px] h-fit">
  <% flash.each do |type, msg| %>
    <div data-controller="notifications" class="<%= flash_class(type) %> relative flex text-white rounded-sm">
      <div class="flex flex-grow justify-center items-center bg-black/20 p-3 max-w-12 text-lg">
        <%= flash_icon(type) %>
      </div>

      <div class="flex justify-center items-center p-3">
        <%= msg %>
      </div>

      <div data-action="click->notifications#closeNotification" class="top-1.5 right-1 absolute text-xs cursor-pointer close-message">
        <i class="fa-solid fa-xmark"></i>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "EventoMundo - " + (content_for(:title) || '') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Preload bg image for login/register pages %>
    <link rel="preload" as="image" href="<%= image_path('koncert.jpg') %>">

    <%# Load favicon %>
    <%= favicon_link_tag asset_path('favicon/favicon.ico') %>

    <%# FontAwesome 7.0.1 library %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%# Leaflet 1.9.4 library %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
 
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/notifications" %>

    <main class="w-full h-[calc(100vh-4rem)]">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_centered_container_wrapper.html.erb
<div class="px-4 py-12 w-full">
  <div class="flex justify-center mx-auto h-fit min-h-full container max-auto">
    <div class="w-full">
      <%= yield %>
    </div>
  </div>
</div>